services:
 
  docs:
    build: 
      context: .
      dockerfile: docs.Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=PRODUCTION
  web:
    build: 
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=PRODUCTION
