services:
 
  client:
    build: 
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    env_file:
      - ./apps/client/.env
    environment:
      - NODE_ENV=PRODUCTION

  admin:
    build: 
      context: .
      dockerfile: admin.Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./apps/admin/.env
    environment:
      - NODE_ENV=PRODUCTION
