services:
 
  client:
    image: ghcr.io/shemaikuzwe/next-turborepo-starter/next-client:${GIT_COMMIT_HASH:-latest}
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=PRODUCTION

  admin:
    image: ghcr.io/shemaikuzwe/next-turborepo-starter/next-admin:${GIT_COMMIT_HASH:-latest}
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=PRODUCTION
      - DATABASE_URL=${DATABASE_URL}
