name: pipeline
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
      - name: Create env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Install dependencies
        run: pnpm install
      - name: Run generate
        run: pnpm prisma generate --schema=./packages/db/prisma/schema.prisma
      - name: Build App
        run: pnpm run build

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Debug - Check env file
        run: |
          echo "=== Checking if .env file exists ==="
          ls -la .env || echo ".env file not found"
          echo "=== Content of .env file (masked) ==="
          if [ -f .env ]; then
            echo "DATABASE_URL=***MASKED***"
            wc -l .env
          fi
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: client.Dockerfile
          push: true
          tags: |
            ghcr.io/shemaikuzwe/next-turborepo-starter/next-client:latest
            ghcr.io/shemaikuzwe/next-turborepo-starter/next-client:${{ github.sha }}
      
      - name: Build and push admin image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: admin.Dockerfile
          push: true
          tags: |
            ghcr.io/shemaikuzwe/next-turborepo-starter/next-admin:latest
            ghcr.io/shemaikuzwe/next-turborepo-starter/next-admin:${{ github.sha }}